### ISSUE TITLE
training a new model

### ISSUE THREAD

**Issue by seekingdeep** [tson1997/LSM#1]
@tson1997 hi there,
using unet for text detection is really robust.

- How to train a new model?

**Comment by sonnguyenasu** [comment]
Hello,
I will update training code for the model soon. In the meantime, you can check out the training code from https://github.com/milesial/Pytorch-UNet .

**Comment by seekingdeep** [comment]
thanks

**Comment by sonnguyenasu** [comment]
I have updated the training code and instructions on how to use it.
