### ISSUE TITLE
Tensorboard Step 0

### ISSUE THREAD

**Issue by seekingdeep** [tson1997/LSM#5]
Hi there,
you have done a great job, LSM is very accurate and robust.

When training,  the tensorboard log seems to be focused on "step 0" and not increasing, while i have reached epoch 400,000
Is this normal?

![tensorboard](https://user-images.githubusercontent.com/71519088/125314683-146c0380-e33f-11eb-9f25-b3202cc2cd81.jpg)

**Comment by sonnguyenasu** [comment]
Hmm, I am not sure, maybe there are bugs in the tensorboard writer, I will check it later.
